Add SIP7 substandard 4 implementation
immutable/seaport-1.4 pull request #30
Opened 2023-07-25 04:38 UTC by frankisawesome

## Motivation
https://github.com/ProjectOpenSea/SIPs/blob/main/SIPS/sip-7.md
Add additional substandard 4 checks to the zone for bulk order hash verification

## Solution

2023-07-25 04:47 UTC, lfportal requested changes

2023-07-25 04:47 UTC, lfportal commented on contracts/zones/ImmutableSignedZone.sol
> +        // context must have at least one orderHashes entry and be a multiple of 32 bytes
Strictly speaking `context` may have no order hash entries for substandard 4.

2023-07-25 04:47 UTC, lfportal commented on contracts/zones/ImmutableSignedZone.sol
> +        bytes calldata orderHashesBytes = context[32:];
**Suggestion:** I think semantically it'd make more sense to perform the length and modulus check on `orderHashesBytes`.

2023-07-25 04:47 UTC, lfportal commented on contracts/zones/ImmutableSignedZone.sol
> +    function _sortBytes32Array(bytes32[] memory arr) internal pure {
Looks like this function is unused.

2023-07-25 04:58 UTC, frankisawesome commented on contracts/zones/ImmutableSignedZone.sol
> +    function _sortBytes32Array(bytes32[] memory arr) internal pure {
[7487f3c](https://github.com/immutable/seaport-1.4/pull/30/commits/7487f3ceff21a4ffb06d39f41efdc4b8db03fd16)

2023-07-25 04:58 UTC, frankisawesome commented on contracts/zones/ImmutableSignedZone.sol
> +        bytes calldata orderHashesBytes = context[32:];
[7487f3c](https://github.com/immutable/seaport-1.4/pull/30/commits/7487f3ceff21a4ffb06d39f41efdc4b8db03fd16)

2023-07-25 04:59 UTC, frankisawesome commented on contracts/zones/ImmutableSignedZone.sol
> +        // context must have at least one orderHashes entry and be a multiple of 32 bytes
[7487f3c](https://github.com/immutable/seaport-1.4/pull/30/commits/7487f3ceff21a4ffb06d39f41efdc4b8db03fd16)

2023-07-25 04:59 UTC, lfportal approved these changes

2023-07-26 00:22 UTC, frankisawesome commented on test/immutablesignedzone.spec.ts
> +    hashes.push(keccak256(`0x123${i >= 10 ? i + "0" : i}`));
This is whacky thing and only works with numbers 0-99..

2023-07-26 01:30 UTC, lfportal approved these changes

2023-07-26 01:30 UTC, merged